/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package etiquetas;

import Beans.bnEtiquetas;
import Beans.bnEtiquetas2;

import Clases.clsEtiquetas;
import Clases.renderTable;
import java.net.URL;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JRViewer;
import utils.utilidades;

/**
 *
 * @author ABAS
 */
public class frmPrincipal extends javax.swing.JFrame {

    private DefaultTableModel miTabla;

    List<bnEtiquetas> informe = new ArrayList<bnEtiquetas>();
    List<bnEtiquetas2> datos = new ArrayList<bnEtiquetas2>();
    String TIPO_UBICAC = "";
    String COD_UBICAC = "";

    int num_total_registros = 0;

    public frmPrincipal() {
        initComponents();

        this.setLocationRelativeTo(null);
        miTabla = (DefaultTableModel) jTable1.getModel();
        jTable1.setDefaultRenderer(Object.class, new renderTable());
        jTable1.getTableHeader().setReorderingAllowed(false);

        DefaultTableCellRenderer renderer = (DefaultTableCellRenderer) jTable1.getTableHeader().getDefaultRenderer();
        renderer.setHorizontalAlignment(0);

        //dar tamaño a columnas
        TableColumnModel columnModel = jTable1.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(60);
        columnModel.getColumn(1).setPreferredWidth(150);
        columnModel.getColumn(2).setPreferredWidth(200);
        columnModel.getColumn(3).setPreferredWidth(350);
        // columnModel.getColumn(3).setPreferredWidth(5);

        buttonGroup1.add(rbtCodigo);
        buttonGroup1.add(rbtFecha);
        buttonGroup1.add(rbtCentroCosto);
        
        jDateChooser1.setEnabled(false);
        jDateChooser2.setEnabled(false);
        txtCentroCosto.setEnabled(false);
        btnCentroCosto.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        rbtCodigo = new javax.swing.JRadioButton();
        rbtFecha = new javax.swing.JRadioButton();
        rbtCentroCosto = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txtDesde = new javax.swing.JTextField();
        txtHasta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCentroCosto = new javax.swing.JTextField();
        btnCentroCosto = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnImprimir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Compras Desde:");

        jDateChooser1.setDoubleBuffered(false);

        jLabel4.setText("Hasta:");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Código activo Desde:");

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Tipo de búsqueda :");

        rbtCodigo.setSelected(true);
        rbtCodigo.setText("Código activo");
        rbtCodigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtCodigoMouseClicked(evt);
            }
        });

        rbtFecha.setText("Fecha");
        rbtFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtFechaMouseClicked(evt);
            }
        });

        rbtCentroCosto.setText("Centro de costo");
        rbtCentroCosto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtCentroCostoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtCentroCosto)
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rbtCodigo)
                    .addComponent(rbtFecha)
                    .addComponent(rbtCentroCosto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Hasta:");

        txtDesde.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDesdeKeyTyped(evt);
            }
        });

        txtHasta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHastaKeyTyped(evt);
            }
        });

        jLabel6.setText("Centro Costo :");

        txtCentroCosto.setEditable(false);

        btnCentroCosto.setText("...");
        btnCentroCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCentroCostoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDesde)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                    .addComponent(txtHasta)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtCentroCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(btnCentroCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(txtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtCentroCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCentroCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        btnImprimir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.setEnabled(false);
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "CODIGO ACTIVO", "DESCRIPCION", "UBICACION"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(22);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(605, 605, 605)
                .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        clsEtiquetas etiquetas = new clsEtiquetas();
        ResultSet rs = null;

        if (rbtCodigo.isSelected()) {

            if (txtDesde.getText().equals("") || txtHasta.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Debe ingresar ambos codigos de activo");
                return;
            }
           
            Long desde = Long.parseLong(txtDesde.getText());
            Long hasta = Long.parseLong(txtHasta.getText());

            if (desde > hasta) {
                JOptionPane.showMessageDialog(null, "El codigo desde debe ser menor o igual al codigo hasta");
                return;
            }

            if (txtDesde.getText().length() < 12) {
                JOptionPane.showMessageDialog(null, "El codigo desde debe ser de 12 digitos");
                return;
            }

            if (txtHasta.getText().length() < 12) {
                JOptionPane.showMessageDialog(null, "El codigo hasta debe ser de 12 digitos");
                return;
            }

            /*..................................................................*/
            rs = etiquetas.mostrarActivos(desde.toString(), hasta.toString());

        } 
        
        if (rbtFecha.isSelected()) {       
            utilidades convertir = new utilidades();
            String fecha1 = convertir.convertDateToString(jDateChooser1.getDate());
            String fecha2 = convertir.convertDateToString(jDateChooser2.getDate());

            if (fecha1 == null || fecha2 == null) {
                JOptionPane.showMessageDialog(null, "Debe ingresar ambas fechas");
                jButton1.setIcon(null);
                return;
            }

            Date inicio = Date.valueOf(fecha1);
            Date fin = Date.valueOf(fecha2);

            if (fin.before(inicio)) {
                JOptionPane.showMessageDialog(null, "La fecha desde debe ser menor o igual a la fecha hasta");
                return;
            }
            rs = etiquetas.mostrarActivos2(inicio, fin);
        }
        if (rbtCentroCosto.isSelected()) {  
            if(txtCentroCosto.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Debe buscar una dependencia");
                return;
            }
            
            rs = etiquetas.mostrarActivosDependencia(TIPO_UBICAC , COD_UBICAC);
        }
        num_total_registros = 0;
        informe.clear();
        limpiarTabla();
        try {
            while (rs.next()) {
                informe.add(new bnEtiquetas(rs.getString("CODIGO_ACTIVO"), rs.getString("CODIGO_ACTIVO").substring(0, 8) + "-" + rs.getString("CODIGO_ACTIVO").substring(8, 12),
                        rs.getString("DESCRIPCION"), rs.getString("UBICAC_FISICA")));
                num_total_registros++;

            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "mal");
            // Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

        if (num_total_registros == 0) {
            JOptionPane.showMessageDialog(null, "No se encontraron registros");
            btnImprimir.setEnabled(false);
            limpiarTabla();
            return;
        }
        btnImprimir.setEnabled(true);
        agreagarRegistros(num_total_registros);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void agreagarRegistros(int num_total_registros) {
        int count = 1;
        for (int i = 0; i < num_total_registros; i++) {

            Object[] fila = new Object[4];
            fila[0] = count;
            fila[1] = informe.get(i).getCODIGO_ACTIVO();
            fila[2] = informe.get(i).getDESCRIPCION();
            fila[3] = informe.get(i).getUBICACION();

            miTabla.addRow(fila);
            count++;
        }
    }

    private void limpiarTabla() {
        try {
            int filas = miTabla.getRowCount() - 1;

            if (filas != -1) {
                for (int i = filas; 0 <= i; i--) {
                    miTabla.removeRow(i);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al limpiar la tabla.");
        }
    }

    private void rbtCodigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtCodigoMouseClicked
        txtDesde.setEnabled(true);
        txtHasta.setEnabled(true);
        jDateChooser1.setEnabled(false);
        jDateChooser2.setEnabled(false);
        txtCentroCosto.setEnabled(false);
        btnCentroCosto.setEnabled(false);

    }//GEN-LAST:event_rbtCodigoMouseClicked

    private void rbtFechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtFechaMouseClicked
        txtDesde.setEnabled(false);
        txtHasta.setEnabled(false);
        jDateChooser1.setEnabled(true);
        jDateChooser2.setEnabled(true);
        txtCentroCosto.setEnabled(false);
        btnCentroCosto.setEnabled(false);

        this.jDateChooser1.getDateEditor().getUiComponent().setEnabled(false);
        this.jDateChooser2.getDateEditor().getUiComponent().setEnabled(false);
    }//GEN-LAST:event_rbtFechaMouseClicked

    private void txtDesdeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDesdeKeyTyped
        validarNumero(txtDesde.getText(), evt);
    }//GEN-LAST:event_txtDesdeKeyTyped

    private void txtHastaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHastaKeyTyped
        validarNumero(txtHasta.getText(), evt);
    }//GEN-LAST:event_txtHastaKeyTyped

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        int count = 0;
        datos.clear();

        for (int i : jTable1.getSelectedRows()) {
            datos.add(new bnEtiquetas2(informe.get(i).getCODIGO_ACTIVO(), informe.get(i).getCODIGO_ACTIVO().substring(0, 8) + "-" + informe.get(i).getCODIGO_ACTIVO().substring(8, 12), informe.get(i).getDESCRIPCION(), informe.get(i).getUBICACION()));
            count++;
        }

        if (count == 0) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar al menos un registro");
            return;
        }
        reporte();
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (evt.getClickCount() == 2) {
            jTable1.getSelectionModel().setSelectionInterval(0, num_total_registros - 1);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnCentroCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCentroCostoActionPerformed
        
        frmBuscarCentroCosto miBusqueda = new frmBuscarCentroCosto(null, rootPaneCheckingEnabled);
        //miBusqueda.setDatos(datos);
        miBusqueda.setLocationRelativeTo(null);
        miBusqueda.setVisible(true);
        String[] dato = new String[3];
        dato = miBusqueda.getRespuesta();
        TIPO_UBICAC = dato[0];
        COD_UBICAC = dato[1];
        
        txtCentroCosto.setText(dato[2]);       
        
    }//GEN-LAST:event_btnCentroCostoActionPerformed

    private void rbtCentroCostoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtCentroCostoMouseClicked
        txtDesde.setEnabled(false);
        txtHasta.setEnabled(false);
        jDateChooser1.setEnabled(false);
        jDateChooser2.setEnabled(false);
        txtCentroCosto.setEnabled(true);
        btnCentroCosto.setEnabled(true);
    }//GEN-LAST:event_rbtCentroCostoMouseClicked
    
    private void validarNumero(String texto, java.awt.event.KeyEvent evt) {
        if (texto.length() == 12) {
            evt.consume();
        }
        int key = (int) evt.getKeyChar();
        if (key < 48 || key > 57) {
            evt.consume();
        }
    }
    private void reporte() {
        try {

            URL url = this.getClass().getResource("rptEtiquetas.jasper");
            String dir = ClassLoader.getSystemResource("etiquetas/logo.jpg").toString();

            JasperReport masterReport = (JasperReport) JRLoader.loadObject(url);
            Map parametro = new HashMap();
            parametro.clear();
            parametro.put("SUBREPORT_DIR", "/");
            parametro.put("logo_p", dir);

            JasperPrint jasperPrint = JasperFillManager.fillReport(masterReport, parametro, new JRBeanCollectionDataSource(datos));

            JRViewer jrv = new JRViewer(jasperPrint);
            jrv.setBounds(6, 6, 720, 470);
            jrv.setVisible(true);

            JFrame jFrame = new JFrame();
            jFrame.setBounds(6, 6, 720, 470);
            jFrame.setLocationRelativeTo(null);
            jFrame.setResizable(false);
            jFrame.add(getContentPane().add(jrv));
            jFrame.setVisible(true);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCentroCosto;
    private javax.swing.JButton btnImprimir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rbtCentroCosto;
    private javax.swing.JRadioButton rbtCodigo;
    private javax.swing.JRadioButton rbtFecha;
    private javax.swing.JTextField txtCentroCosto;
    private javax.swing.JTextField txtDesde;
    private javax.swing.JTextField txtHasta;
    // End of variables declaration//GEN-END:variables
}
